pub mod cookcook;

#[cfg(feature = "anger")]
pub mod anger;
#[cfg(feature = "behavior_tree")]
pub mod behavior_tree;
#[cfg(feature = "brothel")]
pub mod brothel;
#[cfg(feature = "cleanliness")]
pub mod cleanliness;
#[cfg(feature = "combat")]
pub mod combat;
#[cfg(feature = "emotional_dysregulation")]
pub mod emotional_dysregulation;
#[cfg(feature = "formation")]
pub mod formation;
#[cfg(feature = "general_specific_affinity")]
pub mod general_specific_affinity;
#[cfg(feature = "gossip")]
pub mod gossip;
#[cfg(feature = "kelly_criterion")]
pub mod kelly_criterion;
#[cfg(feature = "kill_share")]
pub mod kill_share;
#[cfg(feature = "kits")]
pub mod kits;
#[cfg(feature = "latadog")]
pub mod latadog;
#[cfg(feature = "mate")]
pub mod mate;
#[cfg(feature = "multi_party_dialogue")]
pub mod multi_party_dialogue;
#[cfg(feature = "museum")]
pub mod museum;
#[cfg(feature = "orgasm")]
pub mod orgasm;
#[cfg(feature = "preferences")]
pub mod preferences;
#[cfg(feature = "probing")]
pub mod probing;
#[cfg(feature = "pubsub")]
pub mod pubsub;
#[cfg(feature = "seven_emotions")]
pub mod seven_emotions;
#[cfg(feature = "stock_market_fractal")]
pub mod stock_market_fractal;
#[cfg(feature = "trauma")]
pub mod trauma;
